version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root         # Change to your desired username
      POSTGRES_PASSWORD: YC2jotUPuG5axhDHeARHfL5Wd9mC2shG # Change to your desired password
      POSTGRES_DB: postgres             # Change to your desired database name
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data