spring:
  application:
    name: softlancer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5532/postgres
    password: YC2jotUPuG5axhDHeARHfL5Wd9mC2shG
    username: root

  jpa:
    hibernate:
      ddl-auto: update

web:
  unprotected-routes:  /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /v2/api-docs/**, /swagger-resources/**, /webjars/**, /api/public/**
  jwt-secret: 2SX8tCv36T2vGKCD88m8UKQ2OViNb9k7K4ogFTdhVGzs3suXPZxAATqmr9UZMFft
  jwt-valid-seconds: 3600